learning-process/ppc-2024-mpi-reports

- modules/mpi/shvedova_v_mult_int_simpson/CMakeLists.txt
- modules/mpi/shvedova_v_mult_int_simpson/shvedova_v_mult_int_simpson.tex
Описание целей работы.
Выделение значимости метода для решения практических задач. 
Описание MPI для параллельных вычислений.
Обозначены требования к реализации и составу выполненной задачи.
Описание последовательного алгоритма.
Обобщенное описание распараллеливания алгоритма
Описание применения технологии MPI для реализации схемы распараллеливания.
Приведение характеристик тестовой системы, условий экспериментов и их результатов.
Выводы из результатов эксперимента
Общие выводы по проделанной работе
Основные статьи по MPI и GIT
Код основных функций реализации
> Шведова Виталина. Отчет. Вычисление многомерных интегралов с использованием многошаговой схемы (метод Симпсона).

- modules/mpi/kurakin_m_graham_scan/CMakeLists.txt
- modules/mpi/kurakin_m_graham_scan/kurakin_m_graham_scan.tex
Задача построения выпуклой оболочки заключается в поиске многоугольника, который охватывает переданное множество точек.
Алгоритм Грэхема состоит из нескольких этапов:
1. Среди точек выбирается самая нижняя и самая правая.
2. Все точки сортируются по углу относительно выбранной.
3. Начиная с выбранной точки проходимся по отсортированной последовательности и добавляем точки в окончательную оболочку.
> Куракин Матвей. Отчет. Построение выпуклой оболочки – проход Грэхема.

- modules/mpi/drozhdinov_d_mult_matrix_fox/CMakeLists.txt
- modules/mpi/drozhdinov_d_mult_matrix_fox/drozhdinov_d_mult_matrix_fox.tex
Отчёт о задаче содержит следующие пункты:
**Введение** - рассказывает о проблеме, где встречается, какие способы решения
**Постановка задачи** - описание шагов, которые было необходимо проделать для выполнения лабораторной работы
**Описание алгоритма** - как работает алгоритм, общие обозначения, условия, последовательность действий
**Описание схемы параллелизма** - на чём основан параллельный подход, межпроцессное взаимодействие
**Описание программной реализации** - кратко о использованных в программе структурах и функциях
**Результаты экспериментов** - описание проведенных экспериментов, тестов, обоснование корректности полученного результата
**Заключение** - что мне удалось узнать и применить в ходе лабораторной работы, возможные улучшения
**Литература** - книги, сайты, к которым …
> Дрождинов Дмитрий. Отчет. Умножение плотных матриц. Элементы типа double. Блочная схема, алгоритм Фокса.

- modules/mpi/tsatsyn_a_increasing_contrast_by_histogram/CMakeLists.txt
- modules/mpi/tsatsyn_a_increasing_contrast_by_histogram/tsatsyn_a_increasing_contrast_by_histogram.tex
- Введение
-  Постановка задачи
-  Описание алгоритма
- Описание схемы распараллеливания 
- Результаты экспериментов 
- Заключение 
- Приложение
> Цацын Александр. Отчёт. Повышение контраста полутонового изображения посредством линейной растяжки гистограммы

- modules/mpi/chistov_a_convex_hull_image/CMakeLists.txt
- modules/mpi/chistov_a_convex_hull_image/chistov_a_convex_hull_image.tex
1) Введение: зачем решать задачу построения выпуклой оболочки и где это применяется
2) Постановка задачи: в чем цель работы и какую задачу решаем 
3) Описание алгоритма: описание того в чем заключается алгоритм и его асимптотическая сложность
4) Схема распараллеливания: распределение изображения на части, обработка несколькими процессами, сбор результатов.
5) Экспериментальное исследование: насколько быстрее стал работать алгоритм при распараллеливании, какие изображения тестировались.
6) Заключение: подводятся итоги, выводы из проделанной работы
7) Приложение: код программы
> Чистов Алексей. Отчет. Построение выпуклой оболочки для компонент бинарного изображения.

- modules/mpi/korablev_v_quick_sort_simple_merge/CMakeLists.txt
- modules/mpi/korablev_v_quick_sort_simple_merge/korablev_v_quick_sort_simple_merge.tex
- **Введение:** Представляет быструю сортировку как эффективный алгоритм обработки данных и обосновывает использование параллелизма для её ускорения.
- **Постановка задачи:** Определяет цели разработки, включая реализацию последовательной и параллельной версий алгоритма с тестированием производительности.
- **Описание алгоритма:** Подробно описывает последовательный алгоритм быстрой сортировки с простым слиянием.
- **Описание схемы распараллеливания:** Описывает общую идею разделения данных между процессами и объединения результатов.
- **Описание MPI версии:** Раскрывает реализацию параллельного алгоритма быстрой сортировки с использованием MPI (обертка boost), включая распределение данных и сбор результатов.
- **Результаты экспериментов:** Приводит параметры тестовой систему, описывает …
> Кораблев Владлен. Отчет. Быстрая сортировка с простым слиянием. 

- modules/mpi/ermolaev_v_multidimensional_integral_rectangle/CMakeLists.txt
- modules/mpi/ermolaev_v_multidimensional_integral_rectangle/ermolaev_v_multidimensional_integral_rectangle.tex
1. Введение - описывает актуальность задачи вычисления многомерных интегралов и необходимость применения параллельных вычислений.
2. Постановка задачи - включает:
- Математическую формулировку задачи
- Программную постановку с описанием входных и выходных данных
3. Описание алгоритма - подробное описание метода прямоугольников и его реализации.
4. Схема распараллеливания - описывает:
- Принцип разделения вычислений между процессами
- Особенности реализации параллельного алгоритма
5. Эксперименты - содержит:
- Условия проведения тестов
- Результаты измерений
- Анализ производительности
- Выводы по результатам тестирования
6. Заключение - обобщает результаты работы и описывает практическую значимость.
7. Литература - список использованных источников.
8. Приложение - содержит исходный код …
> Ермолаев Владислав. Отчёт. Вычисление многомерных интегралов с использованием многошаговой схемы  (метод прямоугольников).

- modules/mpi/mironov_a_quick_sort/CMakeLists.txt
- modules/mpi/mironov_a_quick_sort/mironov_a_quick_sort.tex
- **Постановка задачи**  
Формулируется основная проблема и определяются цели и задачи исследования.
- **Описание алгоритма**  
Представляется обзор алгоритма быстрой сортировки, её принципы работы и особенности. Также описывается алгоритм объединения двух отсортированных массивов в один
- **Описание схемы распараллеливания**  
Описывается схема распараллеливания, показывающая распределение задач между процессами.
- **Описание MPI версии**  
Рассматривается реализация алгоритма с использованием MPI. Описываются функции, которые были использованы.
- **Результаты экспериментов**  
Приводятся описание, а потом и результаты экспериментов, направленных на оценку эффективности алгоритма.
- **Заключение**  
Подводятся итоги работы и обобщаются основные результаты.
- **Литература** …
> Миронов Арсений. Отчёт. Быстрая сортировка с простым слиянием.

- modules/mpi/anufriev_d_linear_image/CMakeLists.txt
- modules/mpi/anufriev_d_linear_image/anufriev_d_linear_image.tex
Оглавление
Перечисление разделов отчета с указанием страниц.
Введение
Описание цели работы, актуальности задачи, краткий обзор используемых методов (ядро Гаусса 3x3, вертикальное разбиение, MPI).
Постановка задачи
Формулировка целей проекта: разработка последовательной и параллельной реализаций алгоритма, их тестирование и анализ производительности.
Описание алгоритма
Теоретическое описание Гауссовой фильтрации, структура ядра 3x3, основные этапы обработки изображения.
Описание программных реализаций
Детали реализации последовательной версии алгоритма (SEQ) и параллельной версии с использованием MPI. Описание структур классов, методов, этапов обработки данных.
Результаты и анализ
Тестовые данные, сравнительный анализ производительности, выводы о масштабируемости и эффективности. …
> Ануфриев Даниил. Отчет. Линейная фильтрация изображений (вертикальное разбиение). Ядро Гаусса 3x3.

- modules/mpi/kudryashova_i_graham_scan/CMakeLists.txt
- modules/mpi/kudryashova_i_graham_scan/kudryashova_i_Graham_scan.tex
**Введение**
О важности рассмотрения алгоритмов поиска выпуклой оболочки.
**Постановка задачи**
Базовая информация, необходимая для понимания сути алгоритма Грэхема.
**Описание алгоритма**
Рассматриваем этапы метода Грэхема, такие как выбор начальной точки, сортировка точек, процесс построения выпуклой оболочки, получение результата.
**Временная сложность алгоритма**
Проводим анализ алгоритмической сложности метода Грэхема. Получение его оценки.
**Описание схемы распараллеливания**
Корневой процесс распределяет данные между остальными процессами. Каждый процесс получает свой сегмент данных, с которым и будет работать. Процессы выполняют последовательный алгоритм по поиску выпуклой оболочки на предоставленном им сегменте данных, а затем передают результат на корневой процесс. Корневой …
> Кудряшова Ирина.  Отчет. Построение выпуклой оболочки – проход Грэхема. 

- modules/mpi/malyshev_a_two_dim_global_optimization_characteristics/CMakeLists.txt
- modules/mpi/malyshev_a_two_dim_global_optimization_characteristics/malyshev_a_two_dim_global_optimization_characteristics.tex
**Введение**
Описывает актуальность задачи оптимизации многомерных функций с ограничениями и практическую значимость разработанного алгоритма.
**Постановка задачи**
Формулирует математическую постановку задачи оптимизации функции двух переменных с ограничениями, определяет требования к разрабатываемым алгоритмам.
**Описание алгоритма**
Подробно описывает разработанный алгоритм глобальной оптимизации, включая:
- Инициализацию на равномерной сетке
- Метод локального поиска на основе градиентного спуска
- Метод туннелирования для выхода из локальных минимумов
- Особенности проверки ограничений
**Схема распараллеливания**
Описывает реализацию параллельной версии алгоритма:
- Распределение ограничений между процессами
- Оптимизацию коммуникаций
- Особенности параллельной реализации …
> Малышев Антон. Отчёт. Многошаговая схема решения двумерных задач глобальной оптимизации. Распараллеливание по характеристикам. 

- modules/mpi/zaytsev_bitwise_sort_evenodd_Batcher/CMakeLists.txt
- modules/mpi/zaytsev_bitwise_sort_evenodd_Batcher/zaytsev_bitwise_sort_evenodd_Batcher.tex
Пункты присутствующие в очете:
1. Введение: краткая вводная информация о поразрядной сортировки для целых чисел с четно-нечетным слиянием Бэтчера.
2. Постановка задачи: формулирование цели и основных этапов проекта.
3. Описание алгоритма: краткое описание заданного алгоритма.
4. Описание схемы распараллеливания: объясняется идея работы параллельной версии алгоритма.
5. Результаты экспериментов: предоставляется краткая сводка результатов тестов производительности.
5.1. Подтверждение корректности: описывается подтверждение работы алгоритма.
6. Выводы из результатов: краткий итог по результатам тестов производительности.
7. Заключение: подводятся итоги проектной работы.
8. Литература: список используемой литературы.
9. Приложение: пункт, содержащий части исходного кода проекта.
> Зайцев Денис. Отчет. Поразрядная сортировка для целых чисел с четно-нечетным слиянием Бэтчера.

- modules/mpi/shlyakov_m_ccs_mult/CMakeLists.txt
- modules/mpi/shlyakov_m_ccs_mult/shlyakov_m_css_mult.tex
Данный отчет был реализован по требованиям к критериям из таблицы успеваемости.
Содержание:
1. Введение
3. Описание алгоритма умножения
5.  Тесты производительности
6. Заключение
7. Приложение с кодом
> Шляков Максим. Отчет. "Умножение разреженных матриц. Элементы типа double.  Формат хранения матрицы – столбцовый (CCS)."

- modules/mpi/petrov_a_shell_sort/CMakeLists.txt
- modules/mpi/petrov_a_shell_sort/petrov_a_shell_sort.tex
Отчет по выполненной работе сортировки Шелла с чётно-нечётным слиянием Бетчера.
Выполнил работу Петров Артём из группы 3822Б1ПР2 соблюдая критерии оценивания.
> Петров Артём. Отчёт. Сортировка Шелла с чётно-нечётным слиянием Бетчера.

- modules/mpi/lysov_i_matrix_multiplication_Fox_algorithm/CMakeLists.txt
- modules/mpi/lysov_i_matrix_multiplication_Fox_algorithm/lysov_i_matrix_multiplication_Fox_algorithm.tex
**Отчет содержит следующие разделы:**
1. Введение.
2. Постановка задачи: в чем цель работы.
3. Описание алгоритма: описание того в чем заключается алгоритм.
4. Описание схемы распараллеливания.
5. Результаты экспериментов: ускорение вычисления с помощью алгоритма Фокса относительно стандартного умножения матриц. 
6. Заключение: итоги проделанной работы.
7. Приложение:  код программы.
> Лысов Иван. Отчет. Умножение плотных матриц. Элементы типа double. Блочная схема, алгоритм Фокса.

- modules/mpi/nasedkin_e_strassen_algorithm/CMakeLists.txt
- modules/mpi/nasedkin_e_strassen_algorithm/nasedkin_e_strassen.tex
Содержание:
1. Введение
5. Заключение
6. Литература
7. Приложения
> Наседкин Егор. Отчет. Алгоритм Штрассена.

- modules/mpi/poroshin_v_cons_conv_hull_for_bin_image_comp/CMakeLists.txt
- modules/mpi/poroshin_v_cons_conv_hull_for_bin_image_comp/poroshin_v_cons_conv_hull_for_bin_image_comp.tex
Данный отчет был реализован по требованиям к критериям из таблицы успеваемости.
Содержание:
1) Введение
2) Постановка задачи
3) Описание алгоритма
4) Описание схемы распараллеливания
5) Тесты производительности
6) Заключение
7) Приложение с кодом
> Порошин Владислав. Отчет. "Построения выпуклой оболочки для компонент бинарного изображения."

- modules/mpi/rezantseva_a_rectangle_method/CMakeLists.txt
- modules/mpi/rezantseva_a_rectangle_method/rezantseva_a_rectangle_method.tex
**Введение**
Кратко описываются цель и задачи работы.
**Постановка задачи**
Формальное описание задачи вычисления многомерных интегралов с использованием многошаговой схемы.
**Описание алгоритма**
Краткое описание метода Римана.
**Схема распараллеливания**
Обобщенное описание распараллеливания алгоритма.
**Описание MPI-реализации**
Описание применения технологии MPI и библиотеки Boost для реализации схемы распараллеливания.
**Эксперимент**
Приведение характеристик тестовой системы, условий экспериментов и их результатов. Анализ результатов эксперимента.
**Заключение**
Общие выводы по проделанной работе.
**Список литературы**
Ссылки на источники по многомерным интегралам, интегралу Римана.
**Приложение**
Код с mpi реализацией.
>  Резанцева Анастасия. Отчет. Вычисление многомерных интегралов с использованием многошаговой схемы (метод прямоугольников)

- modules/mpi/smirnov_i_binary_segmentation/CMakeLists.txt
- modules/mpi/smirnov_i_binary_segmentation/smirnov_i_binary_segmentation.tex
Части отчета:
1) Введение
2) Постановка задачи
3) Описание алгоритма
4) Описание схемы распараллеливания
5) Описание MPI-версии
6) Результаты экспериментов
7) Выводы из результатов
8) Заключение
9) Литература
10) Приложение
> Смирнов Илья. Отчет. Маркировка компонент на бинарном изображении.

- modules/mpi/yasakova_t_quick_sort/CMakeLists.txt
- modules/mpi/yasakova_t_quick_sort/yasakova_t_quick_sort.tex
1. Постановка задачи
Формулируется основная проблема и определяются цели и задачи исследования.
2. Описание алгоритма
Представляется обзор алгоритма быстрой сортировки, её принципы работы и особенности. Также описывается алгоритм объединения двух отсортированных массивов в один
3. Описание схемы распараллеливания
Описывается схема распараллеливания, показывающая распределение задач между процессами.
4. Описание MPI версии
Рассматривается реализация алгоритма с использованием MPI. Описываются функции, которые были использованы.
5. Результаты экспериментов
Приводятся описание, а потом и результаты экспериментов, направленных на оценку эффективности алгоритма.
6. Заключение
Подводятся итоги работы и обобщаются основные результаты.
7. Приложение
Представляется исходный код.
> Ясакова Татьяна. Отчет. Быстрая сортировка с простым слиянием.

- modules/mpi/koshkin_m_sobel/CMakeLists.txt
- modules/mpi/koshkin_m_sobel/koshkin_m_sobel.tex
1. Введение
5. MPI-версия - описание программной реализации
7. Выводы из результатов
8. Заключение
9. Литература
10. Приложение
> Кошкин Матвей. Отет. Выделение ребер оператором Собел

- modules/mpi/kharin_m_radix_double_sort/CMakeLists.txt
- modules/mpi/kharin_m_radix_double_sort/kharin_m_radix_double_sort.tex
1. Введение
4. Схема распараллеливания
5. Описание MPI-реализации
7. Выводы
8. Приложение
> Харин Матвей. Отчет. Поразрядная сортировка для вещественных чисел (тип double) с простым слиянием. 

- modules/mpi/gordeeva_t_shell_sort_batcher_merge/CMakeLists.txt
- modules/mpi/gordeeva_t_shell_sort_batcher_merge/gordeeva_t_shell_sort_batcher_merge_report.tex
Краткое описание всего отчета:
1. **Введение**:
- Описание задачи: разработка и параллельная реализация алгоритма сортировки Шелла с использованием четно-нечетного слияния Бэтчера на основе MPI.
- Обоснование выбора алгоритма и параллельной модели для повышения эффективности.
2. **Постановка задачи**:
- Задача заключается в реализации и тестировании алгоритма сортировки Шелла с использованием четно-нечетного слияния Бэтчера, а также в оптимизации его работы с использованием параллельных вычислений.
3. **Описание алгоритма**:
- Подробное описание алгоритма сортировки Шелла с использованием четно-нечетного слияния Бэтчера, который включает этапы поэтапного уменьшения шага сортировки и использование слияния двух отсортированных подмассивов.
4. **Описание схемы распараллеливания**:
- …
> Гордеева Таисия. Задача 3. Вариант 17. Сортировка Шелла с четно-нечетным слиянием Бэтчера

- modules/mpi/sorochkin_d_batcher/CMakeLists.txt
- modules/mpi/sorochkin_d_batcher/sorochkin_d_barcher.tex
1. Введение
5. MPI-версия - описание программной реализации
7. Выводы из результатов
8. Заключение
9. Литература
10. Приложение
> Сорочкин Данила. Отчет. Вариант 21. Поразрядная сортировка для вещественных чисел с четно-нечетным слиянием Бэтчера.

- modules/mpi/korobeinikov_dijkstras_algorithm/CMakeLists.txt
- modules/mpi/korobeinikov_dijkstras_algorithm/korobeinikov_dijkstras_algorithm.tex
1. Введение
Кратко описываются цели и задачи работы, а также общая постановка проблемы
Формальное описание алгоритма Дейкстры на CRS графах,
Рассказывается, как происходит умножение разреженных матриц последовательно (какие основные шаги и структура данных), чтобы затем сопоставить его с параллельной версией.
4. Схема распараллеливания
Кратко описываются принципы разделения работы между процессами (распределение строк, обмен данными, сбор результата) без глубокой детализации конкретных вызовов MPI.
5. Описание MPI-реализации
Более подробно рассматривается, как именно организована передача данных, распределение строк и сбор результатов в вашем конкретном коде с использованием MPI.
Поясняется, на каких графах проводились …
> Коробейников Арсений. Отчёт. Алгоритм Дейкстры на CRS графах.

- modules/mpi/korneeva_e_rectangular_integration/CMakeLists.txt
- modules/mpi/korneeva_e_rectangular_integration/korneeva_e_rectangular_integration.tex
1. Введение
2.1. Цель работы  
2.2. Основные этапы выполнения
3. Реализация последовательной версии метода
3.1. Алгоритм метода  
3.2. Основные структуры данных  
3.3. Описание кода
4. Реализация параллельной версии метода с использованием MPI
4.1. Алгоритм распараллеливания  
4.2. Основные структуры данных  
4.3. Описание кода
5. Сравнение производительности
5.1. Тестирование производительности  
5.2. Сравнение времени выполнения  
5.3. Анализ ускорения и эффективности
6. Заключение
7. Приложение
> Корнеева Екатерина. Отчёт. Вычисление многомерных интегралов с использованием многошаговой схемы (метод прямоугольников).

- modules/mpi/korotin_e_multidimentional_integrals_monte_carlo/CMakeLists.txt
- modules/mpi/korotin_e_multidimentional_integrals_monte_carlo/korotin_e_multidimentional_integrals_monte_carlo.tex
1. Введение
3.1. Последовательная версия
3.2. Описание схемы распараллеливания
3.3. Параллельная версия
3.4. Проверка корректности
4. Результаты экспериментов
5. Выводы из результатов
6. Заключение
7. Литература
8. Приложение
> Коротин Егор. Отчёт. Вариант 10. Вычисление многомерных интегралов методом Монте-Карло.

- modules/mpi/kolodkin_g_hoar_merge_sort_report/CMakeLists.txt
- modules/mpi/kolodkin_g_hoar_merge_sort_report/kolodkin_g_hoar_merge_sort_report.tex
Содержание отчета:
Введение
Постановка задачи
Описание алгоритма
Описание схемы распараллеливания
Программная реализация с помощью MPI
Эксперименты и анализ их результатов
Заключение
Список литературы
Приложения
> Колодкин Григорий. Отчет. Вариант 14. Быстрая сортировка с простым слиянием

- modules/mpi/zolotareva_a_SLE_gradient_method/CMakeLists.txt
- modules/mpi/zolotareva_a_SLE_gradient_method/zolotareva_a_SLE_gradient_method.tex
Введение
Обоснование актуальности метода сопряжённых градиентов (КР) для решения СЛАУ. Основные преимущества: эффективность для разреженных матриц, масштабируемость, возможность параллелизации.
Постановка задачи
Реализация последовательной и параллельной версий метода КР с использованием MPI. Цель — сравнить их производительность и точность.
Теоретические основы
Описание алгоритма КР, требований к матрице ($A$ симметричная и положительно определённая).
Реализация
Последовательная версия: этапы выполнения — валидация, вычисления, постобработка.
Параллельная версия: распределение данных, использование MPI-операций (all_reduce, broadcast).
Результаты экспериментов
Таблицы с замерами времени выполнения. Анализ производительности и ограничения параллельной реализации.
Заключение
Итоги работы и …
> Золотарева Арина.Отчет. Решение систем линейных уравнений методом сопряженных градиентов.

- modules/mpi/zaitsev_a_jarvis/CMakeLists.txt
- modules/mpi/zaitsev_a_jarvis/zaitsev_a_jarvis.tex
1. **Введение:** вводная информация по алгоритму, реализованному в работе, которой посвящен отчет
2. **Постановка задачи:** описание решаемой задачи и требования к реализации
3. **Описание алгоритма:** поэтапное описание алгоритма в его существе
4. **Описание схемы распараллеливания:** описание выбранного способа распределения работы между несколькими процессами
5. **Описание программной реализации:** краткая схема с пояснениями к полученной реализации
6. **Результаты экспериментов:** сводная таблица результатов запуска параллельной программы при разном количестве процессов и разном объеме входных данных в сопоставлении с последовательной версией
7. **Выводы из результатов:** пояснение обнаруженных функциональных зависимостей и некоторых прочих зависимостей
8. **Заключение:** название …
> Зайцев Артем. Отчет. Построение выпуклой оболочки. Проход Джарвиса.

- modules/mpi/gromov_a_convex_hull/CMakeLists.txt
- modules/mpi/gromov_a_convex_hull/gromov_a_convex_hull.tex
- **Введение:** Представляет тему.
- **Постановка задачи:** Определяет цель.
- **Описание алгоритма:** Описывает последовательные этапы алгоритма. 
- **Распараллеливание:** Описывает подходы к разделению данных для параллельной обработки.
- **Тестирование:** Содержит результаты тестов. 
- **Заключение:** Резюмирует основные выводы.
- **Литература:** Список использованных источников.
- **Приложение**
> Громов Алексей. Отчет. Построение выпуклой оболочки для компонент бинарного изображения.

- modules/mpi/gnitienko_k_bellman_ford_algorithm/CMakeLists.txt
- modules/mpi/gnitienko_k_bellman_ford_algorithm/gnitienko_k_bellman_ford_algorithm.tex
Содержание отчета: 
1. Введение
5. MPI-версия - описание программной реализации
7. Выводы из результатов
8. Заключение 
9. Литература
10. Приложение
> Гнитиенко Кирилл. Отчет. Поиск кратчайших путей из одной вершины (алгоритм Беллмана-Форда). С CRS графов.
